name: env_aracore_update
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - plotly
  - seaborn
  - pytest
  - python=3.9.*
  - pip
  - tqdm
  - xlrd
  - goatools
  - numpy
  - scipy
  - pandas
  - pip:
    - cobra
    - colorlover
    - escher
    - optlang
    - tabulate


# name: photosynthesis_bis
# channels:
#   - bioconda
#   - conda-forge
#   - defaults
# dependencies:
#   - plotly=4.14.3
#   - seaborn=0.11.1
#   - pytest=4.6.11
#   - python=3.9.2
#   - pip==21.1
#   - tqdm=4.60.0
#   - xlrd=2.0.1
#   - goatools=1.0.15
#   - numpy==1.20.2
#   - scipy==1.6.2
#   - pandas==1.2.4
#   - pip:
#     - cobra==0.21.0
#     - colorlover==0.3.0
#     - escher==1.7.3
#     - optlang==1.4.4
#     - tabulate==0.8.9